services:
  llm-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-test-app

    # Port mapping
    ports:
      - "3003:3003"

    # Environment variables from .env file
    env_file:
      - .env

    # Override for local development (disable HTTPS redirect)
    # For production deployment, remove this or set NODE_ENV=production
    environment:
      - NODE_ENV=development

    # Volume mounts for persistent data
    volumes:
      # Runtime data (usage tracking, rate limits) - MUST persist across restarts
      - ./src/data:/app/src/data
      # Logs directory (optional)
      - ./logs:/app/logs

    # Restart policy
    restart: unless-stopped

    # Health check (includes x-forwarded-proto header for production HTTPS redirect)
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get({hostname:'localhost',port:3003,path:'/health',headers:{'x-forwarded-proto':'https'}}, (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
